// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(TeacherPlatformDbContext))]
    [Migration("20260907155855_AddTable")]
    partial class AddTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.ClassEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassEnrollments", (string)null);
                });

            modelBuilder.Entity("BusinessObject.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentLevel")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfLessons")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetLevel")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classrooms", (string)null);
                });

            modelBuilder.Entity("BusinessObject.QuestionTypeTask1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypeTask1s", (string)null);
                });

            modelBuilder.Entity("BusinessObject.QuestionTypeTask2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypeTask2s", (string)null);
                });

            modelBuilder.Entity("BusinessObject.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AiScore")
                        .HasColumnType("real");

                    b.Property<string>("CompletionTimeMinutes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradingMode")
                        .HasColumnType("text");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<float?>("Score1")
                        .HasColumnType("real");

                    b.Property<float?>("Score2")
                        .HasColumnType("real");

                    b.Property<float?>("TeacherScore")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("WritingTask1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("WritingTask2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WritingTask1Id");

                    b.HasIndex("WritingTask2Id");

                    b.ToTable("TaskHistories", (string)null);
                });

            modelBuilder.Entity("BusinessObject.TeacherAiRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiFeedbackRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskHistoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherConfidenceRating")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskHistoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAiRatings", (string)null);
                });

            modelBuilder.Entity("BusinessObject.TeacherGradingStar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AiCcScore")
                        .HasColumnType("real");

                    b.Property<float?>("AiGrScore")
                        .HasColumnType("real");

                    b.Property<float?>("AiLrScore")
                        .HasColumnType("real");

                    b.Property<float?>("AiOverallScore")
                        .HasColumnType("real");

                    b.Property<float?>("AiTrScore")
                        .HasColumnType("real");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("boolean");

                    b.Property<int>("TaskHistoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("TaskHistoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherGradingStars", (string)null);
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Createdat")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_User_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BusinessObject.WritingEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric");

                    b.Property<string>("OverallSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<int?>("WritingTask1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("WritingTask2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WritingTask1Id");

                    b.HasIndex("WritingTask2Id");

                    b.ToTable("WritingEvaluations", (string)null);
                });

            modelBuilder.Entity("BusinessObject.WritingTask1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionTypeIdTask1")
                        .HasColumnType("integer");

                    b.Property<int?>("Usersid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeIdTask1");

                    b.HasIndex("Usersid");

                    b.ToTable("WritingTask1s", (string)null);
                });

            modelBuilder.Entity("BusinessObject.WritingTask2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionTypeIdTask2")
                        .HasColumnType("integer");

                    b.Property<int?>("Usersid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeIdTask2");

                    b.HasIndex("Usersid");

                    b.ToTable("WritingTask2s", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaFeedbackDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Quote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("RatingSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("UserRating")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaScoreId");

                    b.ToTable("CriteriaFeedbackDetails", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaImprovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImprovementDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaScoreId");

                    b.ToTable("CriteriaImprovements", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BandReason")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<string>("ScoreAccuracyVote")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VoteSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WritingEvaluationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WritingEvaluationId");

                    b.ToTable("CriteriaScores", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaStrength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("StrengthDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaScoreId");

                    b.ToTable("CriteriaStrengths", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.EvaluationNextStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NextStepDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WritingEvaluationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WritingEvaluationId");

                    b.ToTable("EvaluationNextSteps", (string)null);
                });

            modelBuilder.Entity("BusinessObject.evaluation.EvaluationSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SuggestionDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WritingEvaluationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WritingEvaluationId");

                    b.ToTable("EvaluationSuggestions", (string)null);
                });

            modelBuilder.Entity("BusinessObject.ClassEnrollment", b =>
                {
                    b.HasOne("BusinessObject.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BusinessObject.Classroom", b =>
                {
                    b.HasOne("BusinessObject.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.TaskHistory", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.WritingTask1", "WritingTask1")
                        .WithMany()
                        .HasForeignKey("WritingTask1Id");

                    b.HasOne("BusinessObject.WritingTask2", "WritingTask2")
                        .WithMany()
                        .HasForeignKey("WritingTask2Id");

                    b.Navigation("User");

                    b.Navigation("WritingTask1");

                    b.Navigation("WritingTask2");
                });

            modelBuilder.Entity("BusinessObject.TeacherAiRating", b =>
                {
                    b.HasOne("BusinessObject.TaskHistory", "TaskHistory")
                        .WithMany()
                        .HasForeignKey("TaskHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskHistory");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.TeacherGradingStar", b =>
                {
                    b.HasOne("BusinessObject.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.TaskHistory", "TaskHistory")
                        .WithMany()
                        .HasForeignKey("TaskHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("TaskHistory");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BusinessObject.WritingEvaluation", b =>
                {
                    b.HasOne("BusinessObject.WritingTask1", "WritingTask1")
                        .WithMany()
                        .HasForeignKey("WritingTask1Id");

                    b.HasOne("BusinessObject.WritingTask2", "WritingTask2")
                        .WithMany()
                        .HasForeignKey("WritingTask2Id");

                    b.Navigation("WritingTask1");

                    b.Navigation("WritingTask2");
                });

            modelBuilder.Entity("BusinessObject.WritingTask1", b =>
                {
                    b.HasOne("BusinessObject.QuestionTypeTask1", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeIdTask1");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany()
                        .HasForeignKey("Usersid");

                    b.Navigation("QuestionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.WritingTask2", b =>
                {
                    b.HasOne("BusinessObject.QuestionTypeTask2", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeIdTask2");

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany()
                        .HasForeignKey("Usersid");

                    b.Navigation("QuestionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaFeedbackDetail", b =>
                {
                    b.HasOne("BusinessObject.evaluation.CriteriaScore", "CriteriaScore")
                        .WithMany("FeedbackDetails")
                        .HasForeignKey("CriteriaScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaScore");
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaImprovement", b =>
                {
                    b.HasOne("BusinessObject.evaluation.CriteriaScore", "CriteriaScore")
                        .WithMany("AreasForImprovement")
                        .HasForeignKey("CriteriaScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaScore");
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaScore", b =>
                {
                    b.HasOne("BusinessObject.WritingEvaluation", "WritingEvaluation")
                        .WithMany("CriteriaScores")
                        .HasForeignKey("WritingEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingEvaluation");
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaStrength", b =>
                {
                    b.HasOne("BusinessObject.evaluation.CriteriaScore", "CriteriaScore")
                        .WithMany("Strengths")
                        .HasForeignKey("CriteriaScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriteriaScore");
                });

            modelBuilder.Entity("BusinessObject.evaluation.EvaluationNextStep", b =>
                {
                    b.HasOne("BusinessObject.WritingEvaluation", "WritingEvaluation")
                        .WithMany("NextSteps")
                        .HasForeignKey("WritingEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingEvaluation");
                });

            modelBuilder.Entity("BusinessObject.evaluation.EvaluationSuggestion", b =>
                {
                    b.HasOne("BusinessObject.WritingEvaluation", "WritingEvaluation")
                        .WithMany("Suggestions")
                        .HasForeignKey("WritingEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingEvaluation");
                });

            modelBuilder.Entity("BusinessObject.WritingEvaluation", b =>
                {
                    b.Navigation("CriteriaScores");

                    b.Navigation("NextSteps");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("BusinessObject.evaluation.CriteriaScore", b =>
                {
                    b.Navigation("AreasForImprovement");

                    b.Navigation("FeedbackDetails");

                    b.Navigation("Strengths");
                });
#pragma warning restore 612, 618
        }
    }
}
